### ISSUE TITLE
convert.py, demo.py not work

### ISSUE THREAD

**Issue by hi-one-gg** [LeonLok/Deep-SORT-YOLOv4#14]
When i edit `gpus=4` in convert.py, line 169 it occurs error like this.

>  Traceback (most recent call last):
> File "convert.py", line 172, in <module> 
> yolo4_model = Yolo4(score, iou, anchors_path, classes_path, model_path, weights_path, gpus)
> 
> File "convert.py", line 157, in __init__
> self.load_yolo()
> 
> File "convert.py", line 142, in load_yolo
> self.yolo4_model = multi_gpu_model(self.yolo4_model, gpus=self.gpu_num)
> 
> NameError: name 'multi_gpu_model' is not defined

I can't find "multi_gpu_model" everywhere.. 
How can i solved?

**Comment by ibrandiay** [comment]
my mean ploblem is this error if i execute  python convert.py . help me please

Traceback (most recent call last):
  File "convert.py", line 172, in <module>
    yolo4_model = Yolo4(score, iou, anchors_path, classes_path, model_path, weights_path)
  File "convert.py", line 158, in __init__
    self.load_yolo()
  File "convert.py", line 128, in load_yolo
    conv_weights = np.ndarray(
TypeError: buffer is too small for requested array

**Comment by doubleLLL3** [comment]
I found it in yolo.py:
```
from keras.utils import multi_gpu_model
```
