### ISSUE TITLE
Can't convert my own trained model (Yolov4-csp) 

### ISSUE THREAD

**Issue by P-Cano** [LeonLok/Deep-SORT-YOLOv4#34]
Hi 
I have a problem when converting my model to a .h5 file using the convert file. I had no problems converting from a model trained with yolov4 so I'm guessing there's some value that i need to change in order to be able to convert my file. I'm using the corresponding .txt and weights files for each model so I'm sure that's not the issue. BTW I'm getting this error with the csp model:
.
.
.

Converting  104
Traceback (most recent call last):
  File "convert.py", line 171, in <module>
    yolo4_model = Yolo4(score, iou, anchors_path, classes_path, model_path, weights_path)
  File "convert.py", line 157, in __init__
    self.load_yolo()
  File "convert.py", line 130, in load_yolo
    buffer=weights_file.read(weights_size * 4))
TypeError: buffer is too small for requested array

Thanks and regards!

**Comment by thundo** [comment]
This should be the fix https://github.com/LeonLok/Deep-SORT-YOLOv4/issues/12#issuecomment-896972476
